sys: disable jit on apple >~= aarch64
This disables the JIT on a few targets because it doesn't appear to
build. For example, Clang fails with:

    Undefined symbols for architecture arm64:
      "___clear_cache", referenced from:
          _sljit_generate_code in libforeign.a(pcre2_jit_compile.o)
    ld: symbol(s) not found for architecture arm64

PR #16