error: migrate bindgen install hint to bindgen-cli since 0.61.0
Since [bindgen 0.61.0][changelog], the `bindgen`
CLI binary must be installed via the `bindgen-cli`
crate.

[changelog]: https://github.com/rust-lang/rust-bindgen/blob/main/CHANGELOG.md#0610

PR #39